name: first-workflow
on:
  push:
    branches: [ main ]
jobs:
  first-workflow-jop:
    name: First Job
    runs-on: ubuntu-latest
    steps: 
      - name: before checkout action
        run: ls
        shell: bash
      - name: checkout code
        uses: actions/checkout@v3
      - name: after checkout action
        run: ls
        shell: bash
        

